### ISSUE TITLE
DebFounder not found

### ISSUE THREAD

**Issue by Frenchy7513** [onnarayman/DebFounder#1]
Hello,
I’m having an issue, I followed every step, but when I arrive to step 4, the result is ./DebFounder.sh: not found 
Any help is appreciated. Thanks in advance 
![3E4DE7AE-D3EC-40E8-AAD1-47E544CE01D8](https://user-images.githubusercontent.com/47708066/191134151-95aec57b-604a-4376-bbe5-1a4843d36fef.png)
![314384C7-6E20-474F-8158-BF502DD9DF44](https://user-images.githubusercontent.com/47708066/191134153-2cc1c2e0-c8a8-42d0-b18f-62d250a11aea.png)

**Comment by onnarayman** [comment]
Yo

**Comment by onnarayman** [comment]
You have to put DebFounder.sh in iSH App root directory not your device root directory.

1. Go to Files App
2. You will find a new location called iSH just enable it
3. When you open it you will find a lot of folders find a one called root
4. Move DebFounder.sh file to it
5. Open iSH App and run the following:
6. ``chmod +x DebFounder.sh``
7. ``./DebFounder.sh``
8. Follow instructions

**Comment by onnarayman** [comment]
You have to put DebFounder.sh in iSH App root directory in Files App.

1. Go to Files App
2. You will find a new location called iSH just enable it
3. When you open it you will find a lot of folders find a one called root
4. Move DebFounder.sh file to it
5. Open iSH App and run the following:
6. ``chmod +x DebFounder.sh``
7. ``./DebFounder.sh``
8. Follow instructions
